const CACHE='iq-brain-lab-v1055';const ASSETS=['./','./index.html','./styles.css','./app.js','./manifest.json','./icons/icon-192.png','./icons/icon-512.png','./icons/icon-maskable-512.png','./js/generators/diceGenerator.js','./js/generators/matrixGenerator.js','./js/generators/mixedGenerator.js','./js/engine/questionEngine.js',
  'assets/audio/rain.ogg'
,
  'assets/audio/ocean.ogg'
,
  'assets/audio/forest.ogg'
,
  'assets/audio/fire.ogg'
,
  'assets/audio/night.ogg'
,
  'assets/audio/alpha.ogg'
,
  'assets/audio/deepFocus.ogg'
,
  'assets/audio/study.ogg'
,
  'assets/audio/meditation.ogg'
,
  'assets/audio/pink.ogg'
,
  'assets/audio/brown.ogg'
,
  'assets/audio/white.ogg'
,
  'assets/audio/delta.ogg'
];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==CACHE).map(x=>caches.delete(x)))));self.clients.claim()});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request).then(x=>{const y=x.clone();caches.open(CACHE).then(c=>c.put(e.request,y));return x}).catch(()=>caches.match('./index.html'))))});
